spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://localhost:27017/Client_Delivery

topic:
  kitchen_delivery: kitechen_delivery_topic
  client : client_topic


server:
  port: 8585



